{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-platform.fullname" . }}-secret
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "devops-platform.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ .Values.secret.secretKey | b64enc | quote }}
{{- end }}